# Generated by Django 4.2.8 on 2024-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinterest',
            name='released_date',
            field=models.DateField(default=2, verbose_name='Date of release'),
            preserve_default=False,
        ),
    ]
